name: flutter_onestore_inapp
description: A Flutter plugin for in-app purchases. Exposes APIs for making in-app purchases through the ONEstore.
version: 0.2.0
repository: https://github.com/ONE-store/flutter_plugins/tree/main/flutter_onestore_inapp
issue_tracker: https://github.com/ONE-store/flutter_plugins/issues

environment:
  sdk: '>=2.18.1 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  flutter_lints: ^2.0.0
  mockito: 5.4.1
  test: ^1.16.0

flutter:
  plugin:
    implements: flutter_onestore_inapp
    platforms:
      android:
        package: com.onestorecorp.sdk.flutter.plugins
        pluginClass: OneStoreInAppPlugin


